#!/bin/sh

export NOTIFY_BG_COLOR=${NOTIFY_BG_COLOR:-0x191311}
export NOTIFY_FG_COLOR=${NOTIFY_FG_COLOR:-0x5B8234}
export NOTIFY_BORDER_COLOR=${NOTIFY_BORDER_COLOR:-0}
export NOTIFY_Y=${NOTIFY_Y:-20}
