#!/bin/ksh

set -o csh-history
has_python_arg_complete(){
    [ -r "$1" ] && grep -q "PYTHON_ARGCOMPLETE_OK" "$1"
}
complete_helper() {
    COMP_CMD="${COMP_CMD%% *}"
    unset COMPREPLY
    case "$COMP_CMD" in
        cpm)
            set -A COMPREPLY -- "${CPM_PASSWORD_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/cpm}"/*
            ;;
        git)
            if [ "$COMP_CWORD" -eq 1 ]; then
                set -A COMPREPLY --  $(git help -a | sed -En "s/^\s+([A-z0-9-]*).*/\1/p")
            elif [ "$COMP_CWORD" -eq 2 ]; then
                set -A COMPREPLY --  $(git branch --list | tr -d ":* ")
            fi
            ;;
        *)
            if whence "$COMP_CMD" 1>/dev/null 2>&1 && has_python_arg_complete "$(whence "$COMP_CMD")"; then
                IFS=$(echo -e '\v') set -A COMPREPLY -- $(_ARGCOMPLETE_IFS="$IFS" COMP_POINT=$COMP_POINT COMP_LINE="$COMP_LINE" _ARGCOMPLETE=1 _ARGCOMPLETE_SUPPRESS_SPACE=1 "$COMP_CMD" 8>&1 9>&2 1>/dev/null 2>&1)
            fi
            ;;
    esac
}
