#!/bin/sh
# shellcheck disable=2164,SC2034

alias oneline='git log --oneline'
alias git-branch-recent='git branch --sort=-committerdate'
alias git-push-new='git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)'

export CD_HISTORY=
export CD_REV_HISTORY=

smart_cd() {
    CD_HISTORY="$PWD:$CD_HISTORY"
    CD_REV_HISTORY=
    builtin cd "$@"
}

cd_back() {
    IFS=:
    for path in $CD_HISTORY; do
        CD_HISTORY=${CD_HISTORY#$path:}
        CD_REV_HISTORY="$PWD:$CD_REV_HISTORY"
        builtin cd "$path" && break
    done
    unset IFS
}

cd_forward() {
    IFS=:
    for path in $CD_REV_HISTORY; do
        CD_REV_HISTORY=${CD_REV_HISTORY#$path:}
        CD_HISTORY="$PWD:$CD_HISTORY"
        builtin cd "$path" && break
    done
    unset IFS
}
alias bk=cd_back
alias tg=cd_forward
alias cd=smart_cd
alias F="fg %-" # Cycle between last stopped jobs


[ -n "$KSH_VERSION" ] && . ~/.config/shell/kshrc

#interactive shell specific aliases
find_replace() {
    find . -name "$1" -exec sed -Ei "$2" {} \;
}

find_replace_dryrun() {
    find . -name "$1" -exec sed -En "$2" {} \;
}

kiss_goto() {
    cd "$(kiss s "${1:-${PWD##*/}}" | head -n1 )"
}

export NESTED_SHELL_LEVEL=$((${NESTED_SHELL_LEVEL:--1}+1));

RED='\[\001\e[1;31m\002\]'
GREEN='\[\001\e[1;32m\002\]'
BLUE='\[\001\e[1;34m\002\]'
CYAN='\[\001\e[1;36m\002\]'
END='\[\001\e[0m\002\]'
[ "$NESTED_SHELL_LEVEL" -eq 0 ] || NESTED_SHELL_LEVEL_STR="$NESTED_SHELL_LEVEL"
#interactive shell specific variables
# shellcheck disable=SC2154
alias get_branch='branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null) && echo -en $GREEN[$branch]'

PS1='\[\033]0;$NESTED_SHELL_LEVEL_STR$SESSION_NAME$PWD\007\]'"$CYAN$NESTED_SHELL_LEVEL_STR$END"'$(get_branch)'"$CYAN$SESSION_NAME$BLUE\u@\h$END:"'$( export E=$?; [ "$E" -eq 0 ] && printf "%s" "$GREEN" || printf "%s" "$RED($E)")'"\w$END$ "
